db:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  dbname: "learningDb"
  port: "5432"
mongo:
  user: ""
  password: ""
  host: "localhost"
  dbname: "learningMongo"
  port: "27017"
rabbitmq:
  host: "localhost"
  user: "guest"
  password: "guest"
  port: "5672"
kafka:
  host: "localhost"
  port: "9092"
  numPartitions: 1
  replicationFactor: 1
gin:
  host: "localhost"
  port: "8080"
camunda:
  zeebe-address: ""
  zeebe-client-id: ""
  zeebe-client-secret: ""
  zeebe-authorization-server-url: ""
jwt:
  secret: "806a58ce7c16ec99f11e969ae928d4d48fb508723aa5310a980dd973b94289f0997980fb73cab069428cdded4541b4abe47db82515045fceeb20cdc11da35dee"