db:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  dbname: "learningDb"
  port: "5432"
rabbitmq:
  host: "localhost"
  user: "guest"
  password: "guest"
  port: "5672"
gin:
  host: "localhost"
  port: "8080"
jwt:
  secret: "806a58ce7c16ec99f11e969ae928d4d48fb508723aa5310a980dd973b94289f0997980fb73cab069428cdded4541b4abe47db82515045fceeb20cdc11da35dee"