// Code generated by MockGen. DO NOT EDIT.
// Source: learning_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	. "github.com/AugustoKlaic/golearningstack/pkg/domain/entity"
	. "github.com/AugustoKlaic/golearningstack/pkg/domain/error"
	. "github.com/AugustoKlaic/golearningstack/pkg/domain/repository"
)
